version: "3"

services:
  garment:
    build: .
    environment:
      - PYTHONPATH=/workspace/Garment-Pattern-Generator/packages
    volumes:
      - ./Garment-Pattern-Estimation:/workspace/Garment-Pattern-Estimation
      - ./Garment-Pattern-Generator:/workspace/Garment-Pattern-Generator
    working_dir: /workspace/Garment-Pattern-Estimation
    tty: true